name: Codepropertygraphs Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.13
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.13'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt

    - name: Test with pytest
      env:
        NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
        NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
      run: pytest codepropertygraph/tests
